version: '3.8'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./go-backend/migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql