# Start from the official Go image to build your application
FROM golang:1.21.4 as builder

# Create a directory for your application
WORKDIR /app

# Copy the go.mod and go.sum files first and download the Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of your application's code
COPY . .

# Build your application
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Use a minimal alpine image to run your application
FROM alpine:latest

WORKDIR /root/

# Copy the pre-built binary file from the previous step
COPY --from=builder /app/main .

# Command to run your application
CMD ["./main"]